// <auto-generated />
using System;
using DataWorkService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataWorkService.Migrations
{
    [DbContext(typeof(DbContextSyntheticStock))]
    [Migration("20250329171328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataWorkService.Models.FuturesPriceDifference", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("difference")
                        .HasColumnType("numeric");

                    b.Property<string>("interval")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("symbol1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("symbol2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("FuturesPriceDifferences");
                });
#pragma warning restore 612, 618
        }
    }
}
